---
kind: pipeline
type: docker
name: default

steps:
  - name: yamllint
    commands:
      - yamllint .drone.yml
  - name: hadolint
    image: hadolint/hadolint:2.5.0-alpine
    commands:
      - hadolint Dockerfile
  - name: docker
    image: plugins/docker:19.03.8
    settings:
      username: hsmtkk
      password:
        from_secret: dockerhub_token
      repo: hsmtkk/scaling-rotary-phone
      squash: true
